### PR TITLE
21122 - hide 'Hide Details' button

### PR DESCRIPTION
**Pull request by ketaki-deodhar**
*Issue #:* /bcgov/entity#21122

*Description of changes:*

hide 'Hide Details' button for some filings

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the business-filings-ui license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-filings-dev--pr-657-poeck4xb.web.app

**Review by severinbeauvais — APPROVED** [review]
Looks good. Thanks for the test link.

**Comment by ArwenQin** [comment]
Looks good to me. The "View Details" button is hidden when expanded.

**Comment by severinbeauvais** [comment]
If Karim doesn't have time to look at this, go ahead and merge it anyway.

**Review by JazzarKarim — COMMENTED** [review]
A bit late to the party but LGTM!

**Pull request merged**
