### PR TITLE
17317 - COOPS not in good standing should be able to file

### PR DESCRIPTION
**Pull request by Jxio**
*Issue #:* bcgov/entity#17317

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the business-filings-ui license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-filings-dev--pr-541-yw69b2q3.web.app

**Review by severinbeauvais — APPROVED** [review]
LGTM

**Review by JazzarKarim — APPROVED** [review]
LGTM Jia 👍

**Review by seeker25 — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-filings-dev--pr-541-yw69b2q3.web.app

**Pull request merged**
