### PR TITLE
18284 Updated CSP

### PR DESCRIPTION
**Pull request by severinbeauvais**
*Issue #:* bcgov/entity#18284

*Description of changes:*
- added wss://*.gov.bc.ca to connect-src

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the business-filings-ui license (Apache 2.0).

### CODE REVIEW

**Review by argush3 — APPROVED** [review]

**Review by amanji — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-filings-dev--pr-561-z125qh31.web.app

**Comment by severinbeauvais** [comment]
The problem doesn't seem to be solved on the preview site (see URL above). Should we NOT merge this PR then?

**Comment by severinbeauvais** [comment]
I think this CSP change solves nothing. Closing this PR.

**Comment by severinbeauvais** [comment]
Let's try this fix again...

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-filings-dev--pr-561-z125qh31.web.app

**Pull request merged**
