### PR TITLE
16042 - Consent to Continue Out (change "More actions" button style)

### PR DESCRIPTION
**Pull request by ketaki-deodhar**
*Issue #:* /bcgov/entity#16042

*Description of changes:*
change "More actions" button style

Before (In DEV):

image

After:

image

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the business-filings-ui license (Apache 2.0).

### CODE REVIEW

**Review by JazzarKarim — APPROVED** [review]

**Review by severinbeauvais — APPROVED** [review]
👍

**Comment by severinbeauvais** [comment]
Wait - please fix broken unit tests.

**Comment by ketaki-deodhar** [comment]
> Wait - please fix broken unit tests.



> Wait - please fix broken unit tests.

Oops... Fixing it

**Comment by pwei1018** [comment]
Temporary Url for review: https://business-filings-dev--pr-505-zxchxd8t.web.app

**Comment by pwei1018** [comment]
Temporary Url for review: https://business-filings-dev--pr-505-zxchxd8t.web.app

**Comment by pwei1018** [comment]
Temporary Url for review: https://business-filings-dev--pr-505-zxchxd8t.web.app

**Pull request merged**
