### PR TITLE
21977 Added new filing statuses and partial handling

### PR DESCRIPTION
**Pull request by severinbeauvais**
*Issue #:* bcgov/entity#21977

**This is a partial implementation, to at least display continuation applications in the new statuses instead of showing an error dialog.**

*Description of changes:*
- app version = 7.3.10
- added 4 new filing statuses
- added partial handling for new statuses

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the business-filings-ui license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-filings-dev--pr-680-00htuw03.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-filings-dev--pr-680-00htuw03.web.app

**Review by ArwenQin — APPROVED** [review]
This is great!

**Pull request merged**
