### PR TITLE
Fee code fix for Benefit Company Director Change

### PR DESCRIPTION
**Pull request by lekshmimallika-aot**
*Issue #:* /bcgov/entity#5126

*Description of changes:*
Updates to use the correct code for Benefit Company Free Director Change

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the business-filings-ui license (Apache 2.0).

### CODE REVIEW

**Comment by severinbeauvais** [comment]
Can you confirm that there's no such thing as a "free address change"???

**Comment by lekshmimallika-aot** [comment]
> Can you confirm that there's no such thing as a "free address change"???

Any free change within director ( name/address) uses the code OTCDR or BCCDR depending on the legal type

**Comment by severinbeauvais** [comment]
> > Can you confirm that there's no such thing as a "free address change"???
> 
> Any free change within director ( name/address) uses the code OTCDR or BCCDR depending on the legal type

What about office address change?

**Review by cameron-freshworks — APPROVED** [review]
Code looks good!

**Review by severinbeauvais — APPROVED** [review]

**Pull request merged**
