### PR TITLE
feat: digital credentials gate

### PR DESCRIPTION
**Pull request by amanji**
*Issue #:* /bcgov/entity#18688

*Description of changes:*

* gate digital business card based on Legal API allowable actions
* depends on: https://github.com/bcgov/lear/pull/2337

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the business-filings-ui license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-filings-dev--pr-595-52zvhfi9.web.app

**Comment by argush3** [comment]
app version bump req'd?

**Review by argush3 — APPROVED** [review]

**Review by JazzarKarim — APPROVED** [review]
LGTM!

**Review by severinbeauvais — COMMENTED** [review]
LGTM

**Pull request merged**
