### PR TITLE
21897 - Fixed Upload Coverage to Codecov

### PR DESCRIPTION
**Pull request by JazzarKarim**
*Issue #:* /bcgov/entity#21897

*Description of changes:*
- No more failing on the testing-coverage step anymore!!!

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the business-filings-ui license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-filings-dev--pr-673-tsq3ckv3.web.app

**Review by severinbeauvais — APPROVED** [review]
Awesome!

Are you making this fix to Create UI and Edit UI?

Will someone else fix Namerequest UI and Auth Web?

**Review by ketaki-deodhar — APPROVED** [review]
This is good!

**Comment by JazzarKarim** [comment]
> Awesome!
> 
> Are you making this fix to Create UI and Edit UI?
> 
> Will someone else fix Namerequest UI and Auth Web?

Yup, I'm doing it also for Create UI and Edit UI. I'm doing them all as part of one ticket (https://github.com/bcgov/entity/issues/21897)

As for NR UI and Auth Web, I'm not too sure. I can probably fix them as well actually as part of my ticket or maybe let the two teams know. I'll take care of that!

**Pull request merged**
