### PR TITLE
17108 fixed invalid variable

### PR DESCRIPTION
**Pull request by severinbeauvais**
*Issue #:* bcgov/entity#17108

*Description of changes:*
- app version = 6.6.4
- fixed incorrect "current filing" assignment
- lint fix (automatic)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the business-filings-ui license (Apache 2.0).

### CODE REVIEW

**Review by JazzarKarim — APPROVED** [review]

**Comment by pwei1018** [comment]
Temporary Url for review: https://business-filings-dev--pr-530-g87isukl.web.app

**Review by leodube-aot — COMMENTED** [review]
That was easy, LGTM!

**Comment by severinbeauvais** [comment]
> That was easy, LGTM!

Hah, yes, and if we had typed this properly, it would have been caught earlier!

**Pull request merged**
