### PR TITLE
17159 Update fetchNameRequest

### PR DESCRIPTION
**Pull request by kzdev420**
*Issue #:* /bcgov/entity#17159

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the business-filings-ui license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-filings-dev--pr-579-t0zd69lw.web.app

**Comment by severinbeauvais** [comment]
LGTM. I'll approve after others have reviewed this.

PS If the testing-coverage fails, open details and check if it's an "upload to Codecov" error. If so, just restart this check. It's usually OK the second time. (I've already restarted it this time.)

**Review by tshyun24 — APPROVED** [review]
LGTM!

**Review by severinbeauvais — APPROVED** [review]

**Pull request merged**
