### PR TITLE
cleaned up enum names

### PR DESCRIPTION
**Pull request by severinbeauvais**
*Issue #:* None

*Description of changes:*
- renamed LegalTypes to EntityTypes
- removed unneeded LegalNames
- renamed typeEnum to entityType

The purposes of this change are:
1. to rename the "legal types" enum to be the same as in the Create UI and Edit UI, and which is in line with what the property is named
2. to remove an enum that seemed to overload a schema property

Note that "entity type" is also known by other names, ie:
1. `business.legalType`
2. `filing.business.legalType`
3. `alteration.alterCorpType.corpType`
(and maybe others)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the business-filings-ui license (Apache 2.0).

### CODE REVIEW

**Review by cameron-freshworks — APPROVED** [review]

**Comment by cameron-freshworks** [comment]
Looks good, though should this clean up wait until after Kials changes to the Bcomp identifier? 
Not 100% sure on the changes but BCOMP's would be referred to as `BEN` i think.

**Comment by severinbeauvais** [comment]
> Looks good, though should this clean up wait until after Kials changes to the Bcomp identifier?
> Not 100% sure on the changes but BCOMP's would be referred to as `BEN` i think.

The 'BEN' change is a different ticket.

**Comment by severinbeauvais** [comment]
> So in a perfect world, we would just need to update our Bcomp value in the enum... though that can certainly come later once those changes are commit on the BE.

This is getting us closer to the perfect world where we use the same types, names, etc :)

**Review by kialj876 — APPROVED** [review]

**Comment by severinbeauvais** [comment]
This PR has been reviewed and approved, and I just confirmed that it would not "undo" any changes recently made (ie, BC -> BEN), so now I'm merging it...

**Comment by severinbeauvais** [comment]
Oops, merge conflicts... will fix next.

**Pull request merged**
