### PR TITLE
16761 Completing Party email address needs to be editable for end-user

### PR DESCRIPTION
**Pull request by chenhongjing**
*Issue #:* /bcgov/entity#16761

*Description of changes:*
Before:
image

After:
image

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the business-filings-ui license (Apache 2.0).

### CODE REVIEW

**Review by severinbeauvais — APPROVED** [review]
LGTM

**Comment by chenhongjing** [comment]
Please let me know if there is something I forgot to consider. It's just a very small modification. :sweat_smile:

**Review by JazzarKarim — APPROVED** [review]
👍

**Comment by severinbeauvais** [comment]
I think @bennypc and @leodube-aot should have a quick look to see the change in passing a static prop instead of a dynamic one.

**Pull request merged**
