### PR TITLE
18284: merge feature branch to main branch (digital business card)

### PR DESCRIPTION
**Pull request by severinbeauvais**
*Issue #:* bcgov/entity#18284 + bcgov/entity#18394

*Description of changes:* See PR #552.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the business-filings-ui license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-filings-dev--pr-560-l1buipr2.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-filings-dev--pr-560-l1buipr2.web.app

**Comment by severinbeauvais** [comment]
Akiff, Karim, Argus -- I'm not looking for your review. This is FYI only.

**Comment by severinbeauvais** [comment]
Closing this PR and using #566 instead.

**Pull request closed without merging**
