### PR TITLE
Fix 24953 - Update NoW Per New Designs

### PR DESCRIPTION
**Pull request by ArwenQin**
*Issue #:* /bcgov/entity#24953

*Description of changes:*
- remove POA section text
- add an icon in submit button
- change document delivery section label
- Other changes are pending, discussing with Jacqueline

Jacqueline's UX assurance notes are here:
https://www.figma.com/design/CLqwqGQYARaSrnzLwh6w8Q/Notice-of-Withdrawal?node-id=700-16551&p=f&focus-id=2462-239471&m=dev

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the business-filings-ui license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-filings-dev--pr-709-473wrfuv.web.app

**Comment by ArwenQin** [comment]
For test:
https://business-filings-dev--pr-709-473wrfuv.web.app/BC0883809/notice-of-withdrawal?filingToBeWithdrawn=155118&filingId=0

**Comment by ArwenQin** [comment]
1. remove POA section text
image

2. add an icon in submit button
image

3. change document delivery section label (Registered Office)
image



Other changes are pending, discussing with Jacqueline

**Review by severinbeauvais — APPROVED** [review]
Looks good. Just one thing: use the error class on the inner div (not outer div) to fix the red bar:

image

**Comment by ArwenQin** [comment]
> Looks good. Just one thing: use the error class on the inner div (not outer div) to fix the red bar:
> 
> image

Updated! looks good now

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-filings-dev--pr-709-473wrfuv.web.app

**Review by meawong — APPROVED** [review]
Looks good with the fix!

**Review by eason-pan-bc — APPROVED** [review]
LGTM 😃

**Comment by ArwenQin** [comment]
Thanks reviewers. I want to confirm with Jacqueline tmr and then merge the changes.

**Pull request merged**
