### PR TITLE
17917 Added placeholder for null values

### PR DESCRIPTION
**Pull request by jamespaologarcia**
*Issue #:* /bcgov/entity#17917

Initialized empty strings for null firstNames and middleNames

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the business-filings-ui license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-filings-dev--pr-572-yu4cwk1t.web.app

**Review by severinbeauvais — COMMENTED** [review]
I will approve after others have reviewed.

**Review by JazzarKarim — APPROVED** [review]

**Review by PaulGarewal — APPROVED** [review]
LGTM 👍

**Review by severinbeauvais — APPROVED** [review]

**Pull request merged**
