### PR TITLE
10774_fix_decimal_issue_nr_expiry

### PR DESCRIPTION
**Pull request by ozamani9**
*Issue #:* /bcgov/entity#10774

*Description of changes:*

Fixed NR Expiry Date decimal issue.

### CODE REVIEW

**Review by cameron-freshworks — APPROVED** [review]
Looks good!

**Comment by severinbeauvais** [comment]
Well, you can PR the requested changes :)

**Comment by ozamani9** [comment]
> Well, you can PR the requested changes :)

should i create a NEW branch P.R. for your suggestions, i apologize, i thought it was a quick fix.... didnt want to spend alot of time with unit tests, since all scenerios now have a rounded date

**Comment by severinbeauvais** [comment]
You can use a new branch or you can rebase your current branch to use it again.

The unit tests are always to demonstrate that a fix functions correctly, and to prevent future changes from breaking this :)

**Pull request merged**
